branch-defaults:
  default:
    environment: null
global:
  application_name: sh06-backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
