image: node:latest

stages:
  - install_backend
  - install_frontend
  - start-dev-app
  - test_backend

variables:
  PROJECT_DIR: "sas-forensics"
  FRONTEND_DIR: "sas-forensics/frontend"
  BACKEND_DIR: "sas-forensics/backend"


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/
    - node_modules/


install_backend:
  stage: install_backend
  image: python:3.10
  script:
    - python -m venv venv
    - source venv/bin/activate
    - echo "Created venv OK!"
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "installed pip requirements OK!"
    
  artifacts:
    paths:
      - venv/

install_frontend:
  stage: install_frontend
  image: node:latest
  script:
    - cd $FRONTEND_DIR
    - npm install --legacy-peer-deps
    - echo "Frontend installed OK!"
  artifacts:
    paths:
      - $FRONTEND_DIR/node_modules/


test_backend:
  stage: test_backend
  image: python:3.10
  variables:
    POSTGRES_DB: testdb
    POSTGRES_USER: testuser
    POSTGRES_PASSWORD: testpassword
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - cd $BACKEND_DIR
    - python manage.py migrate
  script:
    - cd $BACKEND_DIR
    - python manage.py test case_api/tests/
  artifacts:
    reports:
      junit: report.xml