image: node:18

stages:
  - install
  - start-dev-app

variables:
  PYTHON_VERSION: "3.10"
  PROJECT_DIR: "sas-forensics"

cache:
  key: ${CI_COMMIT_REF_SLUG}
install:
  stage: install
  script:
    - pip install requirements.txt
    - venv/scripts/activate
    - cd sas-forensics/frontend
    - npm install

start-app:
  stage: start-dev-app
  script:
    - npm start