image: node:18

stages:
  - install
  - start-dev-app

variables:
  PROJECT_DIR: "sas-forensics"

cache:
  key: ${CI_COMMIT_REF_SLUG}
install:
  stage: install
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - cd sas-forensics/frontend
    - npm install

start-app:
  stage: start-dev-app
  script:
    - cd sas-forensics/frontend
    - npm start