image: node:latest

stages:
  - install_backend
  - install_frontend
  - start-dev-app

variables:
  PROJECT_DIR: "sas-forensics"
  FRONTEND_DIR: "sas-forensics/frontend"


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - venv/
    - node_modules/


install_backend:
  stage: install_backend
  image: python:3.10
  script:
    - python -m venv venv
    - source venv/bin/activate
    - echo "Created venv OK!"
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "installed pip requirements OK!"
    
  artifacts:
    paths:
      - venv/

install_frontend:
  stage: install_frontend
  image: node:latest
  script:
    - cd $FRONTEND_DIR
    - npm install --legacy-peer-deps
    - echo "Frontend installed OK!"
  artifacts:
    paths:
      - $FRONTEND_DIR/node_modules/
