# Generated by Django 5.1.3 on 2024-11-17 03:45

import upload.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=upload.utils.upload_to_based_on_type),
        ),
    ]
