branch-defaults:
  default:
    environment: sh06-backend-env
    group_suffix: null
environment-defaults:
  sh06-backend-env:
    branch: null
    repository: null
global:
  application_name: sasforensics-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
