# Generated by Django 5.1.3 on 2025-01-17 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.AddField(
            model_name='file',
            name='file_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'pdf'), ('mp4', 'mp4'), ('jpeg', 'jpeg'), ('docx', 'docx')], max_length=20),
        ),
        migrations.CreateModel(
            name='AnalysedDocs',
            fields=[
                ('Analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('JSON_file', models.FilePathField()),
                ('case_number', models.CharField(blank=True, max_length=20)),
                ('file_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysed_document', to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('type_of_crime', models.CharField(max_length=255)),
                ('date_opened', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('references', models.ManyToManyField(blank=True, related_name='referenced_cases', to='files.case')),
                ('reviewers', models.ManyToManyField(blank=True, related_name='case_reviewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.case'),
        ),
        migrations.CreateModel(
            name='CaseChangelog',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('change_details', models.CharField(max_length=70)),
                ('type_of_change', models.CharField(choices=[('Added Evidence', 'Added Evidence'), ('Updated Information', 'Updated Information'), ('Assigned Detective', 'Assigned Detective'), ('Assigned Reviewer', 'Assigned Reviewer'), ('Created Connection', 'Created Connection'), ('Created Case', 'Created Case')], max_length=50)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_changelog_record', to='files.case')),
                ('change_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocChangelog',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('change_details', models.CharField(max_length=70)),
                ('change_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_changelog_record', to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='UserCaseAccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New Evidence', 'New Evidence'), ('Updated Information', 'Updated Information'), ('No changes', 'No changes')], max_length=50)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_access_records', to='files.case')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_access_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
