# Generated by Django 4.2.18 on 2025-02-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseddocs',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
