# Generated by Django 4.2.18 on 2025-03-04 19:44

import case_api.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_api", "0002_analyseddocs_reviewed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=case_api.utils.upload_to_based_on_type),
        ),
    ]
