# Generated by Django 4.2.18 on 2025-02-28 15:36

import case_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0002_analyseddocs_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyseddocs',
            name='JSON_file',
            field=models.FileField(upload_to=case_api.models.upload_to_based_on_type),
        ),
    ]
