# Generated by Django 4.2.18 on 2025-03-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0003_alter_analyseddocs_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='docchangelog',
            name='analysis_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_changelog_record', to='case_api.analyseddocs'),
        ),
        migrations.AddField(
            model_name='docchangelog',
            name='type_of_change',
            field=models.CharField(choices=[('File Uploaded', 'File Uploaded'), ('File Updated', 'File Updated'), ('File Deleted', 'File Deleted'), ('Analysis Created', 'Analysis Created'), ('Analysis Updated', 'Analysis Updated'), ('Analysis Reviewed', 'Analysis Reviewed')], max_length=50, null=True),
        ),
    ]
