# Generated by Django 4.2.18 on 2025-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0004_docchangelog_analysis_id_docchangelog_type_of_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casechangelog',
            name='type_of_change',
            field=models.CharField(choices=[('Added Evidence', 'Added Evidence'), ('Removed Evidence', 'Removed Evidence'), ('Updated Information', 'Updated Information'), ('Assigned Detective', 'Assigned Detective'), ('Assigned Reviewer', 'Assigned Reviewer'), ('Created Connection', 'Created Connection'), ('Created Case', 'Created Case')], max_length=50),
        ),
    ]
