# Generated by Django 4.2.18 on 2025-03-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0003_alter_file_file'),
        ('case_api', '0004_alter_analyseddocs_json_file'),
        ('case_api', '0005_alter_casechangelog_type_of_change'),
    ]

    operations = [
    ]
